# Cloudflare Workers + Static Assets 配置
name = "nfc-douyin-video"
main = "./server/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 静态资源配置
[assets]
directory = "./client/dist"
not_found_handling = "single_page_application"
html_handling = "auto"

# 环境变量配置
[vars]
NODE_ENV = "production"
API_VERSION = "v1"

# KV命名空间配置
[[kv_namespaces]]
binding = "VIDEO_CACHE"
id = ""  # 部署时需要创建KV命名空间并填入ID
preview_id = ""  # 预览环境KV命名空间ID

# 生产环境配置
[env.production]
name = "nfc-douyin-video"
[env.production.vars]
NODE_ENV = "production"

# 测试环境配置  
[env.staging]
name = "nfc-douyin-video-staging"
[env.staging.vars]
NODE_ENV = "staging"

# 构建配置
[build]
command = "npm run build:all"

# 兼容性设置
[compatibility_flags]
nodejs_compat = true

# 速率限制配置
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

# 路由配置
[[routes]]
pattern = "nfc-douyin-video.workers.dev/*"
zone_name = "workers.dev" 