# Cloudflare Workers + Static Assets 配置
name = "pyp8"
main = "./server/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 静态资源配置
[assets]
directory = "./client/dist"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"

# 环境变量配置
[vars]
NODE_ENV = "production"
API_VERSION = "v1"
# 快子API配置（需要在Cloudflare Workers设置中添加实际值）
# KUAIZI_APP_KEY = "your_app_key"
# KUAIZI_APP_SECRET = "your_app_secret" 
# KUAIZI_ACCOUNT_ID = "your_account_id"
# 抖音API配置
# DOUYIN_APP_ID = "your_douyin_app_id"
# DOUYIN_APP_SECRET = "your_douyin_app_secret"

# KV命名空间配置（需要先创建KV命名空间）
# [[kv_namespaces]]
# binding = "VIDEO_CACHE"
# id = "your_kv_namespace_id"
# preview_id = "your_preview_kv_namespace_id"

# 生产环境配置
[env.production]
name = "pyp6"
[env.production.vars]
NODE_ENV = "production"

# 测试环境配置  
[env.staging]
name = "pyp6-staging"
[env.staging.vars]
NODE_ENV = "staging"

# 构建配置
[build]
command = "npm run build:all" 