# Cloudflare Workers 配置文件
name = "nfc-douyin-video"
main = "worker/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量配置
[vars]
DOMAIN = "https://nfc-douyin-video.workers.dev"
NODE_ENV = "production"
API_VERSION = "v1"

# KV命名空间配置
[[kv_namespaces]]
binding = "VIDEO_CACHE"
id = "" # 需要创建KV命名空间后填入
preview_id = "" # 需要创建预览KV命名空间后填入

# 静态资源配置
[site]
bucket = "./client/dist"

# 环境配置
[env.staging]
name = "nfc-douyin-video-staging"
[env.staging.vars]
DOMAIN = "https://nfc-douyin-video-staging.workers.dev"
NODE_ENV = "staging"

# 速率限制配置
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

# 构建配置
[build]
command = "npm run build"

# 兼容性设置
[compatibility_flags]
nodejs_compat = true

# 路由配置
[[routes]]
pattern = "nfc-douyin-video.workers.dev/*"
zone_name = "workers.dev" 